export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const SEARCH_MOVIES_FAILED = "SEARCH_MOVIES_FAILED";
export const GET_MORE_RESULTS = "GET_MORE_RESULTS";
export const GET_DETAIL = "GET_DETAIL";
export const GET_DETAIL_FAILED = "GET_DETAIL_FAILED";
export const CLEAR_DETAIL = "CLEAR_DETAIL";

